### ISSUE TITLE
Messages Received After OnDisconnectedAsync - Connection Not Fully Closed

### ISSUE THREAD

**Issue by osmancetin10** [vadrsa/SimpleR#19]
Hello,

I recently started using SimpleR on our production OCPP server, where it’s managing an average of 200 connected charge units. Performance has been excellent, with very fast handling and minimal resource consumption.

However, we occasionally encounter an intermittent issue. In some cases, **OnDisconnectedAsync** is triggered, but the connection doesn’t actually close as expected. After **OnDisconnectedAsync**, we sometimes continue to receive messages from the client, such as in **DispatchMessageAsync**, even though **OnConnectedAsync** hasn’t been called again.

![image](https://github.com/user-attachments/assets/ae5e9a7d-eb1e-4712-b8fe-5d53e4402a92)
For example, in the log screenshot attached, you can see that a “StatusNotification” message from the OCPP client arrived after **OnDisconnectedAsync** was already triggered.

Am I handling something incorrectly, or could there be an issue with how connections are managed in this setup?

Thank you for your help.

Best regards.

**Comment by vadrsa** [comment]
Hi @osmancetin10,
Thanks for the feedback, if you could also share some performance stats(e.g. mem usage, latency, etc...) that would be invaluable.

Let me investigate the described issue and come back to you.

**Comment by vadrsa** [comment]
@osmancetin10 Can you provide me with debug logs from the `SimpleR` namespace or a minimal reproducible example?

**Comment by osmancetin10** [comment]
Hi @vadrsa,

Once I’ve gathered the statistics, I’ll share them here. 

Unfortunately, we couldn't replicate the issue in debug mode with the simulator; it only occurs in production with actual charge units. The only logs I can provide are the "OCPP Logs," similar to the screenshot I previously shared.

**Comment by vadrsa** [comment]
What about the logs from the production server, can you put the log level to Debug so that we can see what actually happens in case the issue is reproduced again?

**Comment by vadrsa** [comment]
Also if you can share the dispatcher implementation, that could also help me debug the issue

**Comment by vadrsa** [comment]
Thanks for sharing this @osmancetin10

**Comment by osmancetin10** [comment]
I'll gather and send the debug logs as soon as possible.

**Dispatcher Implementation:**

```
public async Task OnConnectedAsync(IWebsocketConnectionContext<IOcppMessage> connection)
{
    string? ocppId = connection.User.FindFirstValue(ClaimTypes.NameIdentifier);
    if (string.IsNullOrWhiteSpace(ocppId))
    {
        return;
    }

    try
    {
        using var scope = _serviceScopeFactory.CreateScope();
        IChargeUnitService chargeUnitService = scope.ServiceProvider.GetRequiredService<IChargeUnitService>();
        IChargeUnitLogService chargeUnitLogService = scope.ServiceProvider.GetRequiredService<IChargeUnitLogService>();

        ChargeUnit? chargeUnit = await chargeUnitService.GetChargeUnitByOcppIdAsync(ocppId);
        if (chargeUnit == null)
        {
            return;
        }

        _connectionService.AddConnection(ocppId, connection, chargeUnit);

        await chargeUnitLogService.AddChargeUnitCallLogAsync(new ChargeUnitCallLogAddDto(new OcppCall(Guid.NewGuid().ToString("N"), Ocpp16MessageTypes.CHARGE_UNIT_CONNECTED, ""))
        {
            MessageDirection = OcppMessageDirectionTypes.CLIENT_TO_SERVER,
            ChargeUnitId = chargeUnit.Id,
            TenantId = chargeUnit.TenantId
        });

    }
    catch (Exception ex)
    {
        _logger.LogError(ex, "OnConnectedAsync ocppId: {@OcppId}", ocppId);
        _connectionService.RemoveConnection(ocppId);
    }
}

public async Task OnDisconnectedAsync(IWebsocketConnectionContext<IOcppMessage> connection, Exception? exception)
{
    string? ocppId = connection.User.FindFirstValue(ClaimTypes.NameIdentifier);
    if (string.IsNullOrWhiteSpace(ocppId))
    {
        return;
    }

    try
    {
        using var scope = _serviceScopeFactory.CreateScope();
        IChargeUnitService chargeUnitService = scope.ServiceProvider.GetRequiredService<IChargeUnitService>();
        IChargeUnitLogService chargeUnitLogService = scope.ServiceProvider.GetRequiredService<IChargeUnitLogService>();
        
        ChargeUnit? chargeUnit = await chargeUnitService.GetChargeUnitByOcppIdAsync(ocppId);
        if (chargeUnit == null)
        {
            return;
        }

        await chargeUnitLogService.AddChargeUnitCallLogAsync(new ChargeUnitCallLogAddDto(new OcppCall(Guid.NewGuid().ToString("N"), Ocpp16MessageTypes.CHARGE_UNIT_DISCONNECTED, ""))
        {
            MessageDirection = OcppMessageDirectionTypes.CLIENT_TO_SERVER,
            ChargeUnitId = chargeUnit.Id,
            TenantId = chargeUnit.TenantId
        });

    }
    catch (Exception ex)
    {
        _logger.LogError(ex, "OnDisconnectedAsync ocppId: {@OcppId}, exception: {@Exception}", ocppId, exception);
    }
    finally
    {
        _connectionService.RemoveConnection(ocppId);
    }
}

public async Task DispatchMessageAsync(IWebsocketConnectionContext<IOcppMessage> connection, IOcppMessage message)
{
    string? ocppId = connection.User.FindFirstValue(ClaimTypes.NameIdentifier);
    if (string.IsNullOrWhiteSpace(ocppId))
    {
        return;
    }
    
    try
    {
        using var scope = _serviceScopeFactory.CreateScope();
        IChargeUnitService _chargeUnitService = scope.ServiceProvider.GetRequiredService<IChargeUnitService>();
        IOcpp16MessageHandlerService ocpp16MessageHandlerService = scope.ServiceProvider.GetRequiredService<IOcpp16MessageHandlerService>();

        ChargeUnit? chargeUnit = await _chargeUnitService.GetChargeUnitByOcppIdAsync(ocppId);
        if (chargeUnit == null)
        {
            return;
        }

        switch (message)
        {
            case OcppCall callMessage:
                await ocpp16MessageHandlerService.HandleOcpp16CallMessageAsync(chargeUnit, callMessage, connection);
                break;
            case OcppCallResult callResult:
                await ocpp16MessageHandlerService.HandleOcpp16CallResultMessageAsync(chargeUnit, callResult, connection);
                break;
            case OcppCallError callError:
                await ocpp16MessageHandlerService.HandleOcpp16CallErrorMessageAsync(chargeUnit, callError);
                break;
        }
    }
    catch (Exception ex)
    {
        _logger.LogError(ex, "DispatchMessageAsync ocppId: {@OcppId}, message: {@Message}", ocppId, message);
        _connectionService.RemoveConnection(ocppId);
    }
}
```

ConnectionService basically manages(gets, deletes, adds) websocket connections wih keeping in dictionary.

**Comment by vadrsa** [comment]
Since it's practically impossible to get a `DispatchMessageAsync` call after `OnDisconnectedAsync` is called, the only way I can imagine the described scenario happening, without any more info, is if the charger reconnects but an exception occurs in `OnConnectedAsync` before the `chargeUnitLogService ` logs something.

Looking at your implementation this can actually happen because the exception is not propagated to the library, meaning that the connection would not be logged but will not be closed. I would suggest throwing an exception from the `OnConnectedAsync` method call in all cases when you are expecting the connection to close.

Also, assuming that the _connectionService is meant to track actual socket connections, in the `DispatchMessageAsync` method where `_connectionService.RemoveConnection` is called also call `connection.Abort()`.
